name: Continuos Integration

on:
  - push
  - pull_request

jobs:
  check:
    name: Lint and check format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-lock-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Check format
        run: pnpm prettier --check .

      - name: Lint
        run: pnpm lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-lock-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run unit tests
        run: pnpm test
